### ISSUE TITLE
Fix parsing of decimals

### ISSUE THREAD

**Issue by electrum** [trinodb/trino-go-client#1]
The tests require `parse_decimal_literals_as_double=true` since the driver doesn't properly handle decimals (at least inside of arrays). This session property should be removed (it defaults to `false`) so that the default behavior of parsing decimal literals as decimals occurs, which how most people will use Presto. In general, the type conversion tests need to be more comprehensive.

**Comment by nineinchnick** [comment]
Since https://github.com/trinodb/trino-go-client/pull/90 we no longer use/require `parse_decimal_literals_as_double`.
