### ISSUE TITLE
Does trino-go-client support golang sql.NamedArg?

### ISSUE THREAD

**Issue by zclyne** [trinodb/trino-go-client#101]
Hi, I am using this trino client to query our trino database and I cannot figure out how to use golang `sql.NamedArg` with it.
For example, the query function call looks like:
```golang
db.Query("SELECT * FROM prometheus WHERE \"metricName\" = :metric", sql.NamedArg("metric", "cpu_usage"))
```
But I received the following error:
```
 Error executing query: trino: query failed (400 Bad Request): "Invalid X-Trino-Prepared-Statement header: line 1:73: mismatched input ':'. Expecting: 'ALL', 'ANY', 'SOME', <expression>"
```
I have also tried `@metric` but it didn't work either, so I am wondering whether the trino client supports `NamedArg` or not?

My runtime environment is:
- Golang v1.20.6
- trino-go-client v0.313.0

Thank you!

**Comment by nineinchnick** [comment]
Trino doesn't support named parameters, only positional ones.

**Comment by zclyne** [comment]
Thank you!
