### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by Chaho12** [trinodb/trino-go-client#108]
I notice that I get this error when my coordinator is in heavy load while reading data in `rows.Next()`. Is there a timeout while fetching rows.Next?
- I assume that there is issue while getting response from coordinator.

```
trino: query failed (0 ): "Get \"https://trino_url/v1/statement/executing/20240318_081907_03546_ch76y/y269bf9b085430f6e7d0222f3d8f2dc7309a9fdc9/1426\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

My trinoclient is using [retryable](https://github.com/hashicorp/go-retryablehttp), and new Client uses default httpclient with default poold transport setting.
```go
	retryClient := retryablehttp.NewClient()
	retryClient.Logger = nil
	TrinoClient = retryClient.StandardClient()
```

```go
    defer rows.Close()
    if rows != nil {
        ....
        for rows.next() { 
            ...
            err := rows.Scan(results...)
            ...
        }
        err = rows.Err()
	if err != nil {
	    return err <-- error is logged here.
	}
    }
```

So, I was wondering is `setting http.ClientTimeout` recommded? or at least is it ok to set timeout? I couldn't find anything on timeout part.

I thought that if i don't set it, timeout is infinite and no error is responded. 
This doesn't seem to work with retryable library, as it retries only on connection/server errors.
- https://github.com/hashicorp/go-retryablehttp/blob/main/client.go#L459-L470

**Comment by nineinchnick** [comment]
We support passing timeouts in the context when executing the query. It would be an absolute timeout for the whole query execution, not for individual HTTP requests. A custom HTTP client should allow setting additional timeouts per request, using the [Timeout](https://pkg.go.dev/net/http#Client) property.

**Comment by Chaho12** [comment]
Hmm.. do you suggest setting timeout per request? or just leave it as default

**Comment by nineinchnick** [comment]
What do you want to achieve? If you only want to change the default timeout, set it in the context passed when executing the query.

**Comment by Chaho12** [comment]
This is per http request right? I think 60 is enough. Thanks!
