### ISSUE TITLE
access kerberized data

### ISSUE THREAD

**Issue by youaodu** [trinodb/trino-go-client#111]
system：windwos10

Configure Java access to Trino.
![image](https://github.com/trinodb/trino-go-client/assets/49941556/12006729-f432-4875-8287-5a853cce80b9)

trino-go-client config.
![image](https://github.com/trinodb/trino-go-client/assets/49941556/d2ce2d2e-dc48-45e6-bdb4-958d2da97665)

The Java side can connect to Trino, but the Go client prompts an error.

go client error :
[04-24|11:36:23] error querying the database: trino: Error login to KDC: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND

**Comment by youaodu** [comment]
![image](https://github.com/trinodb/trino-go-client/assets/49941556/b28772c2-1d32-4e6d-a623-8a76808c7ec9)
In the Java client, KerberosRemoteServiceName is required. What does he pass in the Go client?

**Comment by youaodu** [comment]
krb5.conf Is
```
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmin.log

[libdefaults]
 default_realm = HADOOP.QIYI.COM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 kdc_timeout = 2000
 forwardable = true
 allow_weak_crypto=true

[realms]
 HADOOP.QIYI.COM = {
  kdc = kdc.qiyi.domain
  kdc = kdc0.qiyi.domain
  kdc = kdc1.qiyi.domain
  kdc = kdc2.qiyi.domain
  kdc = kdc3.qiyi.domain
 }

```

**Comment by nineinchnick** [comment]
I just checked that this is implemented in the `presto-go-driver`: https://github.com/prestodb/presto-go-client/commit/c52a52637959a37fa694ba4aab7b3a79501f24bb

**Comment by youaodu** [comment]
I checked and didn't see the relevant part in the file you mentioned. 
Can you help me find out what the error is?
[04-24|11:36:23] error querying the database: trino: Error login to KDC: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND

**Comment by nineinchnick** [comment]
Sorry, I thought we don't support Kerberos yet, but we do. Unfortunately, there are no integration tests here for it.

From the errors you included, it looks like the principal is not being found in the KDC. Is the `krb5.conf` you included same for the server and the client? I'm not sure if the paths in the logging section would work on a Windows host, but I'd check those for additional errors.

As for the missing `KerberosRemoteServiceName` parameter, this driver uses a hard-coded value of `trino`. But if this would be causing issues, the error would be different, as this is used after logging in and when making an HTTP request.

**Comment by nineinchnick** [comment]
I don't think we configure logging in the Kerberos library used, and it might ignore the logging section in `krb5.conf`.

**Comment by nineinchnick** [comment]
Would it be possible to check the KDC logs for some additional context to find differences between the Go and Java drivers?

**Comment by youaodu** [comment]
krb5.conf should be loaded, because if my Realm is filled in incorrectly, there will be another error.
`KerberosRemoteServiceName` Where can I modify.

**Comment by nineinchnick** [comment]
See the second argument when calling `err = c.kerberosClient.SetSPNEGOHeader(req, "trino/"+req.URL.Hostname())` here: https://github.com/trinodb/trino-go-client/blob/master/trino/trino.go#L458
