### ISSUE TITLE
How to set a custom name to prepared statements, in different connections

### ISSUE THREAD

**Issue by NachoNievaG** [trinodb/trino-go-client#118]
I'm trying to name queries differently to avoid the generic
`EXECUTE _trino_go USING 4`
and get some context (at least in names).
`EXECUTE total_customers_transactions USING 4`
Is there a way to achieve this using the lib via ExecContext() o QueryRowContext()?

I feel like I'm missing something.
Thank you in advanced!

**Comment by nineinchnick** [comment]
I don't think that's possible. It's a bit obvious, but please describe why do you need it - it'll help to discuss potential solutions.
Prepared statements are not that useful in Trino, the server doesn't keep any state for them, and the query text is always sent in the first request.

We can consider implementing [EXECUTE IMMEDIATE](https://trino.io/docs/current/sql/execute-immediate.html) to avoid one additional roundtrip, and you'll be able to see the query text in logs.

**Comment by NachoNievaG** [comment]
Originally I could manage to handle troubleshoot without any specific query naming, but in recent scenarios my query volume execution grew to a scale that is pretty difficult to follow without any query naming to identify the exec in the WebUI. So having a way to identify at first glance with the last queries executed would be an improvement.
I forked a version that uses a `context.Context` value set in the query invoke, tested it out just to have a key name in prepared statements and it worked fairly well. 
And got from this in the web UI:
![image](https://github.com/trinodb/trino-go-client/assets/83428506/e268ad5d-d278-4674-a001-85cfb4b65b15)
To this:
![image](https://github.com/trinodb/trino-go-client/assets/83428506/1c4d6104-766f-4c79-8f3c-29a412c46125)

But as you mentioned, `Execute Immediate` makes sense to, yet sounds quite complex for fairly "low" benefits.
Let me know if i can provide you with more context!

**Comment by nineinchnick** [comment]
@NachoNievaG try setting `explicitPrepare` to false in the connection string or the config struct. This will switch the driver to use `EXECUTE IMMEDIATE` with the full query text visible in query history. If that doesn't solve your problem, feel free to reopen the issue.
