### ISSUE TITLE
 I use QueryContext to query a super long sql (13700 bytes). When there are args parameters, the error http2ErrCodeEnhanceYourCalm (11) will be reported. Has anyone encountered this?

### ISSUE THREAD

**Issue by KarelRoy** [trinodb/trino-go-client#123]
![image](https://github.com/user-attachments/assets/24f18207-30f1-46e1-8a8c-407395d23cdb)

 I use QueryContext to query a super long sql (13700 bytes). When there are args parameters, the error http2ErrCodeEnhanceYourCalm (11) will be reported. Has anyone encountered this?

**Comment by KarelRoy** [comment]
I may have found the reason,
we will put prepare sql in the header with prepared statement method. If the sql is too long, there will be problems. Is it possible to consider a better way to achieve this, such as using "EXECUTE IMMEDIATE"

**Comment by nineinchnick** [comment]
The JDBC client sends the query text in the request body, maybe we should also do it here: https://github.com/trinodb/trino/blob/master/client/trino-client/src/main/java/io/trino/client/StatementClientV1.java#L145

**Comment by KarelRoy** [comment]
> The JDBC client sends the query text in the request body, maybe we should also do it here: https://github.com/trinodb/trino/blob/master/client/trino-client/src/main/java/io/trino/client/StatementClientV1.java#L145

`        Map<String, String> statements = session.getPreparedStatements();
        for (Entry<String, String> entry : statements.entrySet()) {
            builder.addHeader(TRINO_HEADERS.requestPreparedStatement(), urlEncode(entry.getKey()) + "=" + urlEncode(entry.getValue()));
        }`
that seems to be placed in the header. Maybe there is no other way except to modify own ngnix configuration.
