### ISSUE TITLE
Make the driver struct public to support wrapping with hooks

### ISSUE THREAD

**Issue by drscre** [trinodb/trino-go-client#21]
Currently, Trino sql driver struc is not exported, contrary to other common go sql drivers ([MySQL](https://github.com/go-sql-driver/mysql/blob/master/driver.go#L29), [Postgres](https://github.com/lib/pq/blob/master/conn.go#L48)):

```
type sqldriver struct{}
```

This prevents it from being instrumented (wrapped) with tools like [sqlhooks](https://github.com/gchaincl/sqlhooks).

Could we make it public to be able to use it directly?

**Comment by nineinchnick** [comment]
I don't see a reason not to, it's an empty stuct anyway.
