### ISSUE TITLE
Add support to set X-Trino-Extra-Credential header

### ISSUE THREAD

**Issue by stuartcarnie** [trinodb/trino-go-client#22]
The Trino Go client does not provide a mechanism to set `extraCredentials`, which may be needed by some connectors. The Trino HTTP server expects to find a header named `X-Trino-Extra-Credential` per https://github.com/trinodb/trino/blob/8943325421e81990804a64c9f4f4fd1aaf3e2fc9/client/trino-client/src/main/java/io/trino/client/ProtocolHeaders.java#L131-L134

## Possible Solution

1. Extend the URL to accept a query parameter named `extraCredentials` that takes the form `key=value[,key=value,...]` per the requirements of the [Trino source](https://github.com/trinodb/trino/blob/8fb4a95ab491d91dc82f9a566eaa519ddbc2097a/core/trino-main/src/main/java/io/trino/server/HttpRequestSessionContext.java#L398)

2. Set the `X-Trino-Extra-Credential` header similar to here https://github.com/trinodb/trino-go-client/blob/67b9a8c818cc5327fb207e1c3cc5ee0acb84cc1e/trino/trino.go#L304

**Comment by losipiuk** [comment]
Closed with https://github.com/trinodb/trino-go-client/pull/23
