### ISSUE TITLE
Support for more than one header?

### ISSUE THREAD

**Issue by a-urth** [trinodb/trino-go-client#25]
Hello!

We at Lyft would benefit from possibility to pass more than one header in order to correctly handle requests through our custom proxy. But unfortunatelly currently trino client supports only one header - `X-Trino-User` (https://github.com/trinodb/trino-go-client/blob/master/trino/trino.go#L652).

What do You think about adding support for multiple headers? Lets say any header prefixed with `X-Trino`?

If that sounds ok, then I can prepare a PR for that.

Cheers

**Comment by hashhar** [comment]
Seems similar to https://github.com/trinodb/trino-python-client/pull/121 for the Python client.

It makes sense to me. cc: @losipiuk ?

**Comment by nineinchnick** [comment]
Should we close this issue now or are we waiting for a release?

**Comment by hashhar** [comment]
Fixed in https://github.com/trinodb/trino-go-client/pull/31. Will be part of next release.
