### ISSUE TITLE
Numeric gets converted to string in database/sql.DefaultParameterConverter

### ISSUE THREAD

**Issue by longtengz** [trinodb/trino-go-client#30]
I'm trying to use `trino.Numeric` to query a float64 column, but it gets converted to a string type in `database/sql`, and then `serial.go` serializes it as a string instead of `trino.Numeric`, which results in trino complaining I'm comparing float and varchar.

**Comment by longtengz** [comment]
I think a `NamedValueChecker` for `trino.Numeric` is missing, which is why it gets handled by `DefaultParameterConverter` and then converted back to its underlying type `string`.

**Comment by nineinchnick** [comment]
`trino.Numeric` is defined as a string representation of a number, so even if the `NamedValueChecker` would allow it, it would be bound as a string. The only thing the `Serial()` method does for this type is to validate that the string contains a number (using `strconv.ParseFloat(x, 64)`).

Use a cast in your queries:
```
expr = cast(? AS float64)
```

https://github.com/trinodb/trino-go-client/blob/master/trino/serial.go#L36

**Comment by nineinchnick** [comment]
I recently documented passing args to queries and just opened #50 to also mention `trino.Numeric`. It'll close this issue.

If we would consider adding proper support for numeric types, like integers and floats, I think we should open another issue, as it's not only about `trino.Numeric`.
