### ISSUE TITLE
plan to support Update/Insert/Delete ? 

### ISSUE THREAD

**Issue by csimplestring** [trinodb/trino-go-client#32]
Hi, I found the README file said that: 
_Only read operations are supported, such as SHOW and SELECT._

Is there any plan to support Update/Insert/Delete? 

Thanks in advance.

**Comment by nineinchnick** [comment]
A while ago, in #16, I added support for `ExecContext` and implemented methods of the `Result` interface. I only did this to support the `USE` statement. There are no tests for DML statements like INSERT, UPDATE and DELETE, so this statement in the README is correct. But you should try it, as it might not require any extra work.

**Comment by csimplestring** [comment]
@nineinchnick  it works! and it does not require any extra work. Thanks!

**Comment by csimplestring** [comment]
@nineinchnick  does it support transaction? I roughly walked thru the code and figure out this go-client is using TrinoDB REST API to implement the sql driver interface. So I think transaction is not supported due to the stateless in http's nature. But I am not 100% sure.

**Comment by nineinchnick** [comment]
Transaction statements should work, but we don't have tests for this.
