### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by vipin-agarwal** [trinodb/trino-go-client#36]
I am using trino-go-client to connect to Trino cluster and run queries on Hive catalog.

The first query run takes longer time of around 4-5 seconds and any subsequent runs takes half of them for next 3 minutes or so before going back to 4-5 seconds execution time.

Is there any setting I am missing to set or unset?

**Comment by nineinchnick** [comment]
Can you run the same query using [trino-cli](https://trino.io/docs/current/installation/cli.html)? If you get the same times, it's likely it's not an issue with the Go driver, but has something to do with the configuration of your Trino server. You can try asking for help on [Slack](https://trino.io/slack.html), but remember to describe your configuration.
