### ISSUE TITLE
Panic: runtime error: index out of range in driverRows.Next

### ISSUE THREAD

**Issue by Thomasdezeeuw** [trinodb/trino-go-client#65]
I'm hitting a panic that I reproduce pretty well, but not always, it sometimes panics and sometimes doesn't.

I'm using a pretty simple query: `SELECT 1, NULL, 'abc'"`, but I'm not sure if it's relevant.

The relevant part of the backtrace:

```
panic: runtime error: index out of range [1] with length 1

goroutine 125 [running]:
github.com/trinodb/trino-go-client/trino.(*driverRows).Next(0x14000708160, {0x140000aa3f0, 0x9, 0x10667fbb0?})
        /Users/thomas/go/pkg/mod/github.com/trinodb/trino-go-client@v0.308.0/trino/trino.go:1028 +0x2a0
```

After that it's my code calling `trino.driverRows.Next` directly.

Code where the panic happens: https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L1028

This is the state of `trino.driverRows`:

```
// First call to trino.driverRows.Next (Ok):
&{
	ctx:0x14000117980 
	stmt:0x140001153e0 
	queryID:20230104_135631_01766_ysbyr 
	nextURI:https://localhost:8443/v1/statement/queued/20230104_135631_01766_ysbyr/y235c9529065f1ef1da71af639ccea62d7e95fe9e/1 
	err:<nil> 
	rowindex:0 
	columns:[_col0 _col1 _col2] 
	coltype:[0x140001a67e0 0x140001a68c0 0x140001a6930] 
	data:[[1 <nil> abc]] 
	rowsAffected:0 
	statsCh:<nil> 
	doneCh:0x1400056e360
}

// Second call (panics):
&{
	ctx:0x14000117980 
	stmt:0x140001153e0 
	queryID:20230104_135631_01766_ysbyr 
	nextURI:https://localhost:8443/v1/statement/queued/20230104_135631_01766_ysbyr/y235c9529065f1ef1da71af639ccea62d7e95fe9e/1 
	err:<nil> 
	rowindex:1 
	columns:[_col0 _col1 _col2] 
	coltype:[0x140001a67e0 0x140001a68c0 0x140001a6930] 
	data:[[1 <nil> abc]] 
	rowsAffected:0 
	statsCh:<nil> 
	doneCh:0x1400056e360
}
```

I think the following line is incorrect: https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L1010

~~I think `>=` should be changed to `>` since indexing is zero based.~~
~~But what I can't figure out why the current code works sometimes, but panics in the next test run...~~ Incorrect.

**Comment by nineinchnick** [comment]
Thanks for reporting this, but we need a bit more info and be able to reproduce the issue. Are you sure you're not calling `Next()` after it returns `io.EOF`? Can you post a more complete example to reproduce this?

**Comment by Thomasdezeeuw** [comment]
> Thanks for reporting this, but we need a bit more info and be able to reproduce the issue. Are you sure you're not calling `Next()` after it returns `io.EOF`? Can you post a more complete example to reproduce this?

We've using the same code with other SQL packages as well and it's been running fine. I can't share a lot of code at the moment, but it's basically the following:

```go
	scanValues := make([]driver.Value, len(columns))
	for {
		// Read the next row.
		if err := rows.Next(scanValues); err == io.EOF {
			break
		} else if err != nil {
			return nil, nil, err
		}

		// Do something with `scanValues`...
	}
```

I'm currently doing some more debugging, see if I can find the cause.

**Comment by Thomasdezeeuw** [comment]
Ah! I think I found it. `nextURI` is not empty, thus it doesn't return `io.EOF`, but goes to call `fetch`. However that doesn't seem to change `rowindex`.

"enchaning" the code with some good ol' printf debugging
https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L1010-L1019 

```go
	fmt.Printf("0. qr.rowindex: %d, len(qr.data): %d\n", qr.rowindex, len(qr.data))
	if qr.columns == nil || qr.rowindex >= len(qr.data) {
		if qr.nextURI == "" {
			qr.err = io.EOF
			return qr.err
		}
		if err := qr.fetch(); err != nil {
			qr.err = err
			return err
		}
		fmt.Printf("f. qr.rowindex: %d, len(qr.data): %d\n", qr.rowindex, len(qr.data))
	}
	if len(qr.coltype) == 0 {
		qr.err = sql.ErrNoRows
		return qr.err
	}
	for i, v := range qr.coltype {
		if i > len(dest)-1 {
			break
		}
		fmt.Printf("1. qr.rowindex: %d, len(qr.data): %d\n", qr.rowindex, len(qr.data))
		//vv, err := v.ConvertValue(qr.data[qr.rowindex][i])
		data := qr.data[qr.rowindex]
		vv, err := v.ConvertValue(data[i])
		if err != nil {
			qr.err = err
			return err
		}
		dest[i] = vv
	}
	qr.rowindex++
	return nil
```

Prints the following

```
0. qr.rowindex: 1, len(qr.data): 1
f. qr.rowindex: 1, len(qr.data): 1
1. qr.rowindex: 1, len(qr.data): 1
```

In other words, the `if qr.rowindex >= len(qr.data) { ` statement is correct, but it has a `nextURI`, so it calls `fetch`. But that doesn't seem to update `rowindex` (correctly).

**Comment by Thomasdezeeuw** [comment]
> You're not running any other goroutines that could be using the same `rows` struct?

No, I'm certain of that.

**Comment by nineinchnick** [comment]
The only idea I have now is to run a debugger and step through `fetch()` to see why `rowindex` would not be reset or would anything else overwrite it.

**Comment by Thomasdezeeuw** [comment]
> The only idea I have now is to run a debugger and step through `fetch()` to see why `rowindex` would not be reset or would anything else overwrite it.

https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L1141

is getting a `nil` error, which the calling code doesn't consider a problem and thus continue on without chaning the `rowindex`.

Is it expected that `qr.stmt.errors` can return `nil` errors?

**Comment by Thomasdezeeuw** [comment]
Changing https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L1141

To:
```go
		case err = <-qr.stmt.errors:
			if err == nil {
				continue
			}
```

Fixes the issue, but I can't find the source of the `nil` error being send, which might be worth looking into.

**Comment by nineinchnick** [comment]
`qr.stmt.errors` is a channel, so reading `nil` from it means it just got closed. I checked all places where we write to this channel and we always check for non-nil.

Is it possible the `rows` gets closed before `rows.Next()` is called? For reference: https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L588

**Comment by nineinchnick** [comment]
I agree we can make some changes to make the code more robust and avoid panic, but we should first identify the root cause.

**Comment by Thomasdezeeuw** [comment]
> Definitely yes, there should be an actionable error message returned in this case. Would you like to give it a shot and open a PR?

I'm thinking check if the errors channel is closed with `err, ok = <-qr.stmt.errors`, seems like the easiest solution. At that point should we return an error or panic? An error is nicer, but closing the rows/stmt and using it after is also a programming error so panicking also seems acceptable.

**Comment by nineinchnick** [comment]
My approach would be to make `fetch()` reset the state of `driverRows` earlier, so I'd move `qr.rowindex = 0` to before the `for` loop. The whole case for processing the query response doesn't get executed, because the `qr.stmt.queryResponses` channel is empty and we made sure it gets closed last. So we know that `qr.stmt.errors` can be closed. Reading a `nil` error there isn't an issue, and returning it from `fetch()` shouldn't be an issue to, as long as the state of `driverRows` is correct. That's the usual caveat with non-pure functions 😄 

Then in `Next()` we should add another condition to make sure there's data to process after calling `fetch()` to avoid relying on its implementation.

**Comment by Thomasdezeeuw** [comment]
@nineinchnick I didn't quite follow all the changes you were suggestion so I tried my approach first and it seems to work, see https://github.com/trinodb/trino-go-client/pull/66. If you still prefer your approach I can make the changes, let me know.
