### ISSUE TITLE
Any way to extract queryId from result / rows?

### ISSUE THREAD

**Issue by notmahsa** [trinodb/trino-go-client#67]
Problem summary:
I am trying to get the query ID back from Trino, and I am calling the `QueryContext` method. The implementing Rows struct in the Trino code seems to not send it back in anyway that I can find.

Question:
Can I extract the query ID when using something like this? If so, how?
```
	rows, err := trinoDB.QueryContext(ctx, selectStmt, placeholders...)
	if err != nil {
		return nil, err
	}
	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	for rows.Next() {
             ...
        }
```

**Comment by nineinchnick** [comment]
You have to use a progress update callback, since it receives the query ID. Unfotunately, it's not documented yet, but you can check out this test for an example usage: https://github.com/trinodb/trino-go-client/blob/master/trino/trino_test.go#L288
