### ISSUE TITLE
Update Go version to 1.18

### ISSUE THREAD

**Issue by abhioncbr** [trinodb/trino-go-client#69]
- Currently, the project is based on the 1.14 Go version. Let's upgrade the Go version to 1.18
- Also, `golang.org/x/net v0.0.0-20220706163947-c90051bbdb60` package has the [vulnerability ](https://pkg.go.dev/vuln/GO-2023-1571)

**Comment by abhioncbr** [comment]
Please assign the issue to me. Thanks

**Comment by nineinchnick** [comment]
The go version i `go.mod` is the minimum-supported version, and we want to keep it as is. See https://go.dev/doc/modules/gomod-ref#go
