### ISSUE TITLE
Can't update to v0.310.0

### ISSUE THREAD

**Issue by Thomasdezeeuw** [trinodb/trino-go-client#72]
I'm not exactly sure what is wrong, but when I run `go get -u` I get the following error message:

```
go: github.com/trinodb/trino-go-client@v0.310.0: verifying module: checksum mismatch
        downloaded: h1:QHRRrRrOlOKbY2SQloUspfsWyeMTvSl0UksFm/LA4GU=
        sum.golang.org: h1:GjSG/60MdmaZHWmOsUAbpwjElCcgfoem6KvFWeJ0Hss=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

Did something go wrong with tagging v0.310.0, or was it retagged maybe?

**Comment by nineinchnick** [comment]
Do you use some custom proxy? You can check with `go env | grep -i proxy`. I get:
```
GONOPROXY=""
GOPROXY="https://proxy.golang.org,direct"
```

I ran `go get -u` in one of my projects that uses this driver and it completed successfully. Now I have this:
```
% grep trino go.sum
github.com/trinodb/trino-go-client v0.310.0 h1:GjSG/60MdmaZHWmOsUAbpwjElCcgfoem6KvFWeJ0Hss=
github.com/trinodb/trino-go-client v0.310.0/go.mod h1:ts5yo4ZScOPgQ88m3YwFrV24PvRZr1LNfTMFaGQEjAc=
```

So looks like the checksum you get from `sum.golang.org` is correct.

To help, we'll need more detailed steps to reproduce the problem.

**Comment by Thomasdezeeuw** [comment]
Still not sure what went wrong as I don't use a proxy, but `GOPROXY="https://proxy.golang.org,direct" GONOPROXY="" go get -u` worked. I got the same checksums as you listed and on sum.golang.org. Maybe my local cache got corrupted somehow?

In any case I'm going to close this. Thanks for the quick response @nineinchnick!
