### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by sjones94549** [trinodb/trino-go-client#79]
This trino library has [far more dependencies](https://github.com/trinodb/trino-go-client/blob/master/go.mod) than the [old presto one](https://github.com/prestodb/presto-go-client/blob/master/go.mod), like `github.com/Microsoft/go-winio`, and specifically `github.com/docker/docker`, which isn't clearly related to trino, but conflicts with my application's dependencies. Is it possible to reduce these?

**Comment by mosabua** [comment]
I am not a go person but this sounds reasonable. Any insights here @nineinchnick ?

Also @sjones94549 .. if you have any specific improvements please send PRs..

**Comment by nineinchnick** [comment]
We only use docker for tests. I can try to separate tests into another package, if that's not tej case already.

**Comment by nineinchnick** [comment]
I cannot reproduce the issue.


I tested this by creating a new project:
```bash
mkdir trino-go-example
cd trino-go-example
go mod init github.com/nineinchnick/trino-go-example
cat <EOF >main.go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/trinodb/trino-go-client/trino"
)

func main() {
	db, err := sql.Open("trino", "http://example@localhost:8080")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	var name string
	err = db.QueryRow("select node_id from system.runtime.nodes limit 1").Scan(&name)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(name)
}
EOF
go mod tidy
# just to make sure this compiles and runs
go run ./...
```

This produces the following `go.mod`:
```
module github.com/nineinchnick/trino-go-example

go 1.20

require github.com/trinodb/trino-go-client v0.311.0

require (
	github.com/hashicorp/go-uuid v1.0.3 // indirect
	github.com/jcmturner/gofork v1.7.6 // indirect
	golang.org/x/crypto v0.9.0 // indirect
	gopkg.in/jcmturner/aescts.v1 v1.0.1 // indirect
	gopkg.in/jcmturner/dnsutils.v1 v1.0.1 // indirect
	gopkg.in/jcmturner/gokrb5.v6 v6.1.1 // indirect
	gopkg.in/jcmturner/rpc.v1 v1.1.0 // indirect
)
```


Can you give a bit more details about the conflict you're seeing?

**Comment by nineinchnick** [comment]
But you're using the docker client explicitly in main.go. You're not creating a Trino client there, but a Docker client. That's why it shows up in dependencies.

**Comment by sjones94549** [comment]
that's my scenario -- I have code that uses a docker client at version 1.13, but if I `go get` the trino client, it upgrades to an incompatible docker client 20.10. I'd like to use the trino client, but can't with the incompatible docker upgrade, unless I exclude it in go.mod

**Comment by mosabua** [comment]
Two thoughts:

* I wish go had test scope dependencies like Maven
* From what I can tell the recommendation for Go is to have a separate module for the tests

And I might be wrong ..

**Comment by nineinchnick** [comment]
I've prepared #80 earlier, but now we have a better reproduction scenario. I'll try it out tomorrow and will update the description of that PR.

**Comment by nineinchnick** [comment]
Extracting tests into a separate package doesn't help, dependencies are processed at the module level.

The only workaround for this is to exclude the particular dependency version, like you mentioned before:
```bash
go mod edit -exclude 'github.com/docker/docker@v20.10.17+incompatible'
```
which adds this to `go.mod`:
```
exclude github.com/docker/docker v20.10.17+incompatible
```

**Comment by sjones94549** [comment]
Thanks for trying, @nineinchnick and @mosabua -- it's odd that one has to know these details of external libraries to know what to exclude. Maybe one day this will be improved.

**Comment by mosabua** [comment]
Dependency management is a big issue in every language ecosystem. Some do it better .. others are worse. Sorry there is nothing better at the moment for Go.
